### ISSUE TITLE
First Bar should also be striped if it is not fully contained in query

### ISSUE THREAD

**Issue by ElJocho** [GIScience/ohsome-now-stats-frontend#103]
E.g. a yearly interval and a query time from 01.06.2017 - 31.12.2024 would suggest a wrong value for the first bar which would be labeled 2017 but only contain 7 months of data. Adding stripes there, like we do for the last bar under the same conditions, could increase clarity that this bar is not to be taken at face value.

**Comment by mmerdes** [comment]
good catch
