### ISSUE TITLE
Change all time related interaction with User in their local time

### ISSUE THREAD

**Issue by mrkhan** [GIScience/ohsome-now-stats-frontend#24]
Currently, the user inputs the time but it's sent to the API in UTC and the response is also displayed in UTC which is unknown to the user. It's better that under the hood the time is converted to user's local time and all interaction with the server happens in UTC

**Comment by austin-killman5** [comment]
Hi there I am applying for a job at HeiGIT and decided to write some code to this repo as part of my Application. I didn't have write access so I couldn't make a PR but I did create a fork of the repo and create a PR here if you want to use this code: 
https://github.com/GIScience/ohsome-now-stats-frontend/pull/89

**Comment by ElJocho** [comment]
Hey @austin-killman5, thanks for your contribution, your code looks nice and clean. I do not have insight into the application process, but I wish you good luck with the process :).
