### ISSUE TITLE
better title for the timeseries plot

### ISSUE THREAD

**Issue by Hagellach37** [GIScience/ohsome-now-stats-frontend#41]
the title of the timeseries plot should be adjusted. currently it says: "Chart based on interval"

This should be changed to a dynamic title based on the stats type and the interval
* contributors per month
* total edits per day

(or something similar)

**Comment by Hagellach37** [comment]
additionally add a hint that you can switch the stats type (contributors, total edits, ...) by clicking on the legend.

**Comment by ElJocho** [comment]
-> Current status is that we want to remove the title entirely right?

**Comment by Hagellach37** [comment]
agreed.
