### ISSUE TITLE
Change interval based on Date range selection

### ISSUE THREAD

**Issue by mrkhan** [GIScience/ohsome-now-stats-frontend#43]
Change interval based on Date range selection. For eg: 

- If the user selects a range that consists of multiple years then interval should be `yearly`
- Only year, multiple months then `monthly`
- and so on .... 
- For custom range, use default i.e. `monthly`

**Comment by ElJocho** [comment]
-> we now restrict interval to at least daily if users request more than a one year duration. Otherwise I do not think we should mess too much with user input, that could get annoying for more experienced users
