### ISSUE TITLE
Make it easier for users to find existing hashtags

### ISSUE THREAD

**Issue by mrkhan** [GIScience/ohsome-now-stats-frontend#53]
Users will not always know what all Hashtags are used in OSM, so provide an Autocomplete feature in hashtag field

**Comment by Hagellach37** [comment]
We have also received this feedback from other people: How do users know about existing changeset hashtags?

**Comment by mmerdes** [comment]
The backend query would be reasonably fast as soon as the user starts typing and we have a prefix for the indexed `hashtag` column.

**Comment by ElJocho** [comment]
2bb9556 -> now hashtags are ordered by frequency
