### ISSUE TITLE
Get updated time range that is supported by backend

### ISSUE THREAD

**Issue by mrkhan** [GIScience/ohsome-now-stats-frontend#56]
Since our backend will be updated with new data every minute, the frontend should get an updated time range that is supported by the backend.

**Comment by ElJocho** [comment]
connected to https://github.com/GIScience/ohsome-now-stats-frontend/issues/61

**Comment by ElJocho** [comment]
could have been addressed in [37505b1](https://github.com/GIScience/ohsome-now-stats-frontend/commit/37505b164acfc6f89c0956e15eff1ce4c72ba037) as well -> we now query metadata before other requests which should also adjust the max value
