### ISSUE TITLE
Add legend to map

### ISSUE THREAD

**Issue by SlowMo24** [GIScience/ohsome-now-stats-frontend#63]
To understand the content of the map one has to navigate to the info-tab and scroll down a bit. Adding a legend to the map (circle size and colour) would help understanding and also interpreting it.

In my personal feeling "the lighter the colour the higher the value" is counter-intuitive but that may be personal gusto and our cartography experts may have more experience on that ;-)

**Comment by ElJocho** [comment]
@Hagellach37 any feedback on that?
