### ISSUE TITLE
correctly encode ? in hashtag filter

### ISSUE THREAD

**Issue by Hagellach37** [GIScience/ohsome-now-stats-frontend#64]
The website should properly encode a `?` character in the hashtags filter.

Currently querying for `missing?maps` results in the following request: 
* https://stats.now.ohsome.org/api/stats/missing?maps

The correct URL would be:
* https://stats.now.ohsome.org/api/stats/missing%3Fmaps

**Comment by ElJocho** [comment]
@Hagellach37 this currently then also display the encoded hashtag in the search field, liek it also does for when leading hashtags etc are cleaned. Is that an issue, or is it ok?
