### ISSUE TITLE
use ohsome-format response for /stats endpoint

### ISSUE THREAD

**Issue by Hagellach37** [GIScience/ohsome-now-stats-frontend#67]
The website should consume the response from the /stats endpoint in the ohsome-format.

* https://stats.now.ohsome.org/api/stats/opencitieslac?startdate=2022-08-15T12:39:18.000Z&enddate=2023-08-15T12:39:18.000Z&ohsomeFormat=true

note the additional `ohsomeFormat=true` in the URL.

**Comment by ElJocho** [comment]
8588095
