### ISSUE TITLE
use default values when parameters are not provided in URL

### ISSUE THREAD

**Issue by Hagellach37** [GIScience/ohsome-now-stats-frontend#69]
currently there is a bug when the URL doesn't contain the values for `start` and `end` or `interval`.

e.g. this url https://stats.now.ohsome.org/dashboard#hashtags=missingmaps should be properly displayed and resolved to default values.

**Comment by rtroilo** [comment]
I think this issiue is not entirely solved. 
start/end/interval should be entire duration monthly.

as an example go to this page
- https://www.missingmaps.org/partners/morganstanley/
here you  see the highest hashtag is msmapathonemea with 20622 edits.
When I follow the link I want to see the same number 20622, the month it happend and the locations on the map!
Which in this case is 2021-06.

**Comment by ElJocho** [comment]
@rtroilo the default range for the frontend is just the last year, so that is intended behavior currently

**Comment by rtroilo** [comment]
Thank you @ElJocho for taking care of this issue ❤️
