### ISSUE TITLE
Allow users to select pre-defined list of countries

### ISSUE THREAD

**Issue by Hagellach37** [GIScience/ohsome-now-stats-frontend#77]
It should be easier for users of the website to select all the countries which belong to a certain HOT priority region. The regions contain about ~20 countries and it is very tedious to select one after the other.

Having a "shortcut" for HOT's regional hubs would be a good addition. For instance this could be a small button for each hub which then triggers the selection of the corresponding countries.

We might just use small icons for each hub, e.g. listed here: https://www.hotosm.org/hubs/

Asia Pacific HOT-TM mapping 2023:
* https://stats.now.ohsome.org/dashboard#hashtags=hotosm-project-*&start=2023-01-01T14:52:00.000Z&end=2023-11-13T13:59:42.000Z&interval=P1W&countries=AFG,BGD,BTN,BRN,KHM,TLS,FSM,FJI,IND,IDN,KIR,LAO,MYS,MMR,NPL,PAK,PNG,PHL,SLB,LKA,TON,UZB,VUT,VNM,YEM 

Latin America and Caribbean HOT-TM Mapping 2023:
* https://stats.now.ohsome.org/dashboard#hashtags=hotosm-project-*&start=2023-01-01T14:52:00.000Z&end=2023-11-13T13:59:42.000Z&interval=P1M&countries=ATG,BLZ,BOL,BRA,CHL,CRI,DMA,DOM,ECU,SLV,GTM,GUY,HTI,HND,JAM,MEX,NIC,PAN,PER,TTO,URY,VEN 

Western & Northern Africa HOT-TM Mapping 2023
* https://stats.now.ohsome.org/dashboard#hashtags=hotosm-project-*&start=2023-01-01T14:52:00.000Z&end=2023-11-13T13:59:42.000Z&interval=P1M&countries=DZA,BEN,BFA,CMR,CPV,CAF,TCD,CIV,GNQ,GHA,GIN,GNB,LBR,MLI,MRT,MAR,NER,NGA,STP,SEN,SLE,GMB,TGO 

Eastern & Southern Africa HOT-TM Mapping 2023
* https://stats.now.ohsome.org/dashboard#hashtags=hotosm-project-*&start=2023-01-01T14:52:00.000Z&end=2023-11-13T13:59:42.000Z&interval=P1M&countries=AGO,BDI,COM,COD,DJI,EGY,SWZ,ETH,KEN,LSO,MDG,MWI,MUS,MOZ,NAM,RWA,SOM,SSD,SDN,TZA,UGA,ZMB,ZWE

**Comment by mmerdes** [comment]
I take it these lists are relatively stable, i.e. not change very often?
