### ISSUE TITLE
Handle umlaut in hashtags

### ISSUE THREAD

**Issue by mrkhan** [GIScience/ohsome-now-stats-frontend#83]
Steps to reproduce

1. Click "türkiyeeq060223" from the trending hashtags
2. Change another parameter like, change Time interval to "daily"
3. Click "Get Statistics"

The hashtag textfield and param in URL is changed to "t%C3%BCrkiyeeq060223"
If user clicks again, more special characters are added to hashtag and resulting in no data displayed

**Comment by martien-176** [comment]
This also happens with other special characters, eg â ġ ç ă (to name a few).
