### ISSUE TITLE
Update Documentation/Help on website

### ISSUE THREAD

**Issue by ElJocho** [GIScience/ohsome-now-stats-frontend#85]
# Help Page

* *add the section below to the website*

----
### How to refine your query
In addition to the query parameters mentioned above you can refine your query by specifying (1) a list of countries and (2) a list of additional topics.

![image](https://github.com/GIScience/ohsome-now-stats-frontend/assets/7045979/9cff4fe4-4821-4a40-bea2-0676228d0a7c)

1. Select one or more countries in the drop down menu. You can use this filter to make sure that the summary statistics and timeline statistics correspond only to your countries of interest. You can use the buttons below the drop down menu to select a pre-defined list of countries which refers to the countries covered by HOT's regional hubs.

2. If you are interested in more detailed statistics beyond building and road mapping you can select one or more additional topics in the drop down menu. Each topic represents a specific subset of OSM mapping activity. Check below for a detailed description of each topic.

---

## Update Big Number Calculation Information
* *I would adjust this section on the website and put the information into a table. This will make it easier for us to add more and more topics.*
* *the first sentence of the description can be used as a tooltip*
* *use the icons that you already use on the website*
* *I would adjust the note about negative numbers. Just put this note on top or below the table*

| Icon | Topic Name | Description | OSM Tag Filter |
| --- | --- | --- |---| 
| | Contributors |  The number of distinct users that edited OSM data for the hashtag and the time range defined in your query.</br></br> In the map plot this number refers to the location of the map edits, not the location or origin of the mappers themselves. Such private information and other demographic information (e.g. age, gender) of mappers is not stored in the OSM database. | none | 
![image](https://github.com/GIScience/ohsome-now-stats-frontend/assets/7045979/6e157b58-585c-48f6-a8db-c2c1cb492a88) | Total Map Edits | The number of all OSM edits to "primary map features" for the hashtag and the time range defined in your query.</br></br> Total Map Edits consider only OSM elements with the tag keys defined in the OSM Wiki as [Map Features](https://wiki.openstreetmap.org/wiki/Map_features). We consider edits to all OSM types (nodes, ways, relations) and the following OSM tag keys: | `aerialway=* or aeroway=* or amenity=* or barrier=* or boundary=* or building=* or craft=* or emergency=* or geological=* or healthcare=* or highway=* or historic=* or landuse=* or leisure=* or man_made=* or military=* or natural=* or office=* or place=* or power=* or public_transport=* or railway=* or route=* or shop=* or sport=* or telecom=* or tourism=* or water=* or waterway=*` |
| | Δ Buildings |The absolute increase or decrease in the amount of buildings in the OSM database induced by mapping activity for the hashtag and the time range defined in your query.</br></br> Δ Buildings = Buildings<sub>created</sub> - Buildings<sub>deleted</sub></br></br> Buildings are defined as all OSM ways or relations which hold the tag key building and one of the following tag values:  |`building in (yes, house, residential, detached, detached, garage, apartments, shed, hut, industrial)` |
| | Δ km of Roads | The absolute increase or decrease in the road network length in kilometers in the OSM database induced by mapping activity for the hashtag and the time range defined in your query.</br></br> Δ Roads [km] = Roads<sub>created</sub> + Δ Roads<sub>modified-longer</sub> - Δ Roads<sub>modified-shorter</sub> - Roads<sub>deleted</sub> [km]</br></br>  Roads are defined as all OSM ways or relations which hold the tag key highway and one of the following tag values. These are the principal tag values for the road network, link roads and special road types as defined in the [OSM Wiki](https://wiki.openstreetmap.org/wiki/Map_features#Highway). | `highway in (motorway, trunk, motorway_link, trunk_link, primary, primary_link, secondary, secondary_link, tertiary, tertiary_link, unclassified, residential, living_street, service, pedestrian, track, bus_guideway, escape, raceway, road, busway )` |
| | Δ km of Waterways | The absolute increase or decrease in linear water features length in kilometers in the OSM database induced by mapping activity for the hashtag and the time range defined in your query.</br></br>Δ Waterways [km] = Waterways<sub>created</sub> + Δ Waterways<sub>modified-longer</sub> - Δ Waterways<sub>modified-shorter</sub> - Waterways<sub>deleted</sub> [km] </br></br> Here we only consider the main waterway types as defined in the [OSM Wiki](https://wiki.openstreetmap.org/wiki/Waterways).|`waterway in (river, canal, stream, brook, drain, ditch)` |
| | Δ Amenities |The absolute increase or decrease in the amount of amenities in the OSM database induced by mapping activity for the hashtag and the time range defined in your query.</br></br> Δ Amenities = Amenities<sub>created</sub> - Amenities<sub>deleted</sub></br></br>  According to the [OSM Wiki](https://wiki.openstreetmap.org/wiki/Key:amenity) `amenity` is the top-level tag describing useful and important facilities for visitors and residents, such as toilets, telephones, banks, pharmacies, prisons and schools |`amenity=*` |
|| Δ Places |The absolute increase or decrease in the amount of places in the OSM database induced by mapping activity for the hashtag and the time range defined in your query.</br></br> Δ Places = Places<sub>created</sub> - Places<sub>deleted</sub></br></br> According to the [OSM Wiki](https://wiki.openstreetmap.org/wiki/Places) places include populated settlements of various sizes.  | `place in (country, state, region, province, district, county, municipality, city, borough, suburb, quarter, neighbourhood, town, village, hamlet, isolated_dwelling)` |
| | Δ Healthcare Facilities | The absolute increase or decrease in the amount of healthcare facilities in the OSM database induced by mapping activity for the hashtag and the time range defined in your query.</br></br> Δ Healthcare Facilities =Healthcare Facilities<sub>created</sub> - Healthcare Facilities<sub>deleted</sub></br></br> The filter definition is based on the [HOT Export Tool for HDX configuration](https://export.hotosm.org/en/v3/configurations/detail/b96a923b-8b43-437b-9dce-b4fb09530750) which considers all major healthcare services. | `healthcare=* or amenity in (doctors, dentist, clinic, hospital, pharmacy)`|
| | Δ km² of Land Use Land Cover |The absolute increase or decrease in land use area in square kilometers in the OSM database induced by mapping activity for the hashtag and the time range defined in your query</br></br>Δ Land Use Land Cover [km²] = Land Use Land Cover<sub>created</sub> + ΔLand Use Land Cover<sub>modified-bigger</sub> - Δ Land Use Land Cover<sub>modified-smaller</sub> - Land Use Land Cover<sub>deleted</sub> [km²] </br></br>  The definition used here includes well established tags for coherent areas at the most atomic level available defined by [OQAPI](https://github.com/GIScience/ohsome-quality-api/blob/main/ohsome_quality_api/topics/presets.yaml#L486). This definition therefore excludes areas with the keys aeroway, highway, leisure and tourism which can be found in other sources. |`landuse=* or natural in (bare_rock, beach, dune, fell, glacier, grassland, heath, landslide, mud, rock, sand, scree, scrub, shingle, water, wetland, wood) or waterway in (boatyard, dam, dock, riverbank)` |
| | Δ Social Facilities + Shelters |The absolute increase or decrease in the amount of social facilities and shelters in the OSM database induced by mapping activity for the hashtag and the time range defined in your query.</br></br> Δ Social Facilities = Social Facilities<sub>created</sub> - Social Facilities<sub>deleted</sub></br></br>  According to the [OSM Wiki](https://wiki.openstreetmap.org/wiki/Key:social_facility) a social facility is consdered as any place where social services are conducted.|  `social_facility=* or amenity in (shelter, social_facility, refugee_site)` | 
| | Δ Education Facilities |The absolute increase or decrease in the amount of education facilities in the OSM database induced by mapping activity for the hashtag and the time range defined in your query.</br></br> Δ Education Facilities = Education Facilities<sub>created</sub> - Education Facilities<sub>deleted</sub></br></br>  The filter definition is based on the [HOT Export Tool for HDX configuration](https://export.hotosm.org/en/v3/configurations/detail/b96a923b-8b43-437b-9dce-b4fb09530750) which considers all major education facilities.|`amenity in (kindergarten, school, college, university) or building in (kindergarten, school, college, university)` |
| | Δ Water, Sanitation and Hygiene (WASH) Facilities | The absolute increase or decrease in the amount of WASH facilities in the OSM database induced by mapping activity for the hashtag and the time range defined in your query.</br></br> Δ WASH Facilities = WASH Facilities<sub>created</sub> - WASH Facilities<sub>deleted</sub></br></br> WASH consists of access to drinking water services, sanitation services and hygiene. | `amenity in (toilets, shower, drining_water, water_point) or man_made in (water_tap, borehole, water_works, pumping_station, pump, wastewater_plant, storage_tank, water_well, water_tower, reservoir_covered, water_tank)` |
| | Δ Commercial Facilities |The absolute increase or decrease in the amount of shops in the OSM database induced by mapping activity for the hashtag and the time range defined in your query.</br></br> Δ Commercial Facilities = Commercial Facilities<sub>created</sub> - Commercial Facilities<sub>deleted</sub></br></br> According to the [OSM Wiki](https://wiki.openstreetmap.org/wiki/Key:shop) mappers use `shop=*` to mark the location of a shop and the products that it sells. | `shop=*` |  
| | Δ Financial Services |The absolute increase or decrease in the amount of facilities providing financial services in the OSM database induced by mapping activity for the hashtag and the time range defined in your query.</br></br> Δ Financial Services = Financial Services<sub>created</sub> - Financial Services<sub>deleted</sub></br></br> The definition is based on the tag values listed in the [OSM Wiki](https://wiki.openstreetmap.org/wiki/Key:amenity#Financial).| `amenity in (atm, bank, money_transfer, bureau_de_change, mobile_money_agent)` | 

# Tooltips
- *appears on hover on the questionmark in the big number section*

- [x] use the first sentence of the topic description listed above

# About Page
* [ ] add Missing Maps logo next to HOT logo and add the following sentence:

---

ohsomeNow stats is the replacement for the Missing Maps leaderboard. We are currently evaluating with the Missing Maps partners how we can also provide user-related statistics in accordance with the General Data Protection Regulation (GDPR).

---

**Comment by Hagellach37** [comment]
@ElJocho I think the version above could be used for the website. Let me know if you have additional questions.
