### ISSUE TITLE
"live mode"

### ISSUE THREAD

**Issue by ElJocho** [GIScience/ohsome-now-stats-frontend#95]
Only toggle-able if time is somewhere of the last X hours

-> then refresh page every x minutes to show new stats.

This would improve usability for mapathons, where the stats are displayed at the front

**Comment by Hagellach37** [comment]
to achieve this "manuall" you could do the following:

- enter your hashtag and pick last day
- adjust the url and set the end time to a timestamp in the future, e.g. the time until your mapathon runs
- manually reload the website once in a while

**Comment by mcauer** [comment]
I would prefer a smooth update of components (maybe animated) instead of a site-reload with reloading all the form and button elements having a blank screen for a moment and a visual disruption.

**Comment by mmerdes** [comment]
If you take into account that some browsers allow for automatic periodic update, @Hagellach37 's 'manual' suggestion becomes viable.

**Comment by mrkhan** [comment]
houston we got a LIVE mode 📶
