### ISSUE TITLE
also support minutely interval as dropdownoption

### ISSUE THREAD

**Issue by ElJocho** [GIScience/ohsome-now-stats-frontend#96]
-> also useful for mapathon/short timeframe analysis

-> currently it is doable via manipulating the url, but it would be nice to "officially" supporting it as well

**Comment by Hagellach37** [comment]
probably 5 minutes or 10 minutes would be a sufficient interval for mapathons.

**Comment by ElJocho** [comment]
added 5 min interval and additionally "last 3 hours" as time frame quick selection
