### ISSUE TITLE
Provide csv downloads with a more meaningful name, include some or all query parameter (user experience)

### ISSUE THREAD

**Issue by rtroilo** [GIScience/ohsome-now-stats-frontend#98]
Currently if you like to download the provided csvs the filenames are
- summary, time_interval and data_per_country 

no matter what the query parameters are.

For a user experience it would be usefull to include some or all query-parameters into the filename as well.
Like (suggestion)

- ohsome-now-stats_HASHTAG_START-DATE_END-DATE_summary.csv
- ohsome-now-stats_HASHTAG_START-DATE_END-DATE_interval.csv

**Comment by mrkhan** [comment]
I suggest we also have `countries` in the filename as well. 

- ohsome-now-stats_HASHTAG_START-DATE_END-DATE_COUNTRIES_summary.csv
- ohsome-now-stats_HASHTAG_START-DATE_END-DATE_COUNTRIES_interval.csv

**Comment by Hagellach37** [comment]
I think with countries it could get very very long in some cases. So I would probably not add it.

**Comment by mmerdes** [comment]
Yes, this could get rather long. On the other hand, using ISO codes for the countries would make this viable in many cases.
